version: "3"
services:
  app-socket:
    image: taniwhy/mochi-match-websocket:latest
    container_name: "mochi-match-socket"
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    command: ["npm", "start"]
    depends_on:
      - "redis"

  redis:
    image: "redis:4.0.6"
    container_name: "redis"
    ports:
      - "6379:6379"

networks:
  default:
    external:
      name: shared
