FORMAT: 1A
HOST: http://localhost

# Sample API
sample api

## ルームへの参加 [POST /v1/room/{r_id}/entry/{u_id}]
ユーザーを任意のルームにジョインさせる

+ Parameters
    + r_id: 1 (number) - roomのID
    + u_id: 1 (number) - userのID

+ Response 200 (application/json)
    + Body
        ```
        {
            "message": "Successful entry."
        }
        ```

## ルームへの退室 [DELETE /v1/room/{r_id}/leave/{u_id}]
ユーザーを任意のルームから退室させる

+ Parameters
    + r_id: 1 (number) - roomのID
    + u_id: 1 (number) - userのID

+ Response 200 (application/json)
    + Body
        ```
        {
            "message": "Successful exit."
        }
        ```